wandb_version: 1

model:
  desc: null
  value:
    family: EncoderTF
    n_embd: 64
    n_layer: 12
    n_head: 8
    n_dims: 20
    n_positions: 101
    encoder_activation: relu
    normalize_attn: true
wandb:
  desc: null
  value:
    project: in-context-training-encoder
    entity: in-context
    notes: ''
    log_every_steps: 100
    name: linear_regression
inherit:
  desc: null
  value:
  - /Users/yuenc2/Desktop/transformers-as-statisticians/src/conf/base_encoder.yaml
training:
  desc: null
  value:
    data: gaussian
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 300001
    curriculum:
      dims:
        start: 20
        end: 20
        inc: 1
        interval: 2000
      points:
        interval: 2000
        inc: 2
        end: 41
        start: 41
    tasks:
    - name: linear_regression
      kwargs:
        normalize_w: true
    resume_id: null
    lasso_guided_opt_token: -1
    num_training_examples: null
    learning_rate_override: false
    optimizer_reset: false
    lasso_guided_opt_layer: -2
    lasso_guided_opt_lam: 1.0
    num_tasks: null
    lasso_guided_opt: false
config:
  desc: null
  value: conf/encoder/linear_regression.yaml
out_dir:
  desc: null
  value: ../encoder_final/linear_regression/61bff554-39db-4b59-b695-27bf5c14c078
test_run:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.8.12
    cli_version: 0.16.1
    framework: xgboost
    huggingface_version: 4.33.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702764659.778447
    t:
      1:
      - 1
      - 5
      - 6
      - 11
      - 49
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.12
      5: 0.16.1
      6: 4.33.3
      8:
      - 5
      13: darwin-arm64
