config: conf/encoder/linear_regression.yaml
inherit:
- /Users/yuenc2/Desktop/transformers-as-statisticians/src/conf/base_encoder.yaml
model:
  encoder_activation: relu
  family: EncoderTF
  n_dims: 20
  n_embd: 64
  n_head: 8
  n_layer: 12
  n_positions: 101
  normalize_attn: true
out_dir: ../encoder_final/linear_regression/3f820e3c-513e-425a-89b1-6e59c9e24d50
test_run: false
training:
  batch_size: 64
  curriculum:
    dims:
      end: 20
      inc: 1
      interval: 2000
      start: 20
    points:
      end: 41
      inc: 2
      interval: 2000
      start: 41
  data: gaussian
  keep_every_steps: 100000
  lasso_guided_opt: false
  lasso_guided_opt_lam: 1.0
  lasso_guided_opt_layer: -2
  lasso_guided_opt_token: -1
  learning_rate: 0.0001
  learning_rate_override: false
  num_tasks: null
  num_training_examples: null
  optimizer_reset: false
  resume_id: null
  save_every_steps: 1000
  tasks:
  - kwargs:
      normalize_w: true
    name: linear_regression
  train_steps: 300001
wandb:
  entity: in-context
  log_every_steps: 100
  name: linear_regression
  notes: ''
  project: in-context-training-encoder
